### ISSUE TITLE
Criar Telas

### ISSUE THREAD

**Issue by enzoggqs** [UnBArqDsw2021-1/2021.1_G6_Curumim_Front-end#3]
### Descrição:
Issue direcionada para o desenvolvimento das telas estáticas da aplicação.

### Tarefas:
- [x] Divisão das telas entre a equipe;
- [ ] Criação das telas.

### Critérios de aceitação:
- [ ] Todas as telas propostas estarem criadas

**Comment by Bruno-Felix** [comment]
### Bruno:
- ISSUE -> ADM  Home 
- ISSUE -> PROF Home
- ISSUE -> Cadastro e Login (Auntenticação/ login e persistência)

### Enzo e Gabriel:
- ISSUE -> ADM Cadastrar professor
- ISSUE -> ADM Cadastrar aluno
- ISSUE -> PROF Criar Atividade
- ISSUE -> ADM Criar evento
- ISSUE -> ADM Criar Turma
- ISSUE -> PROF criar anotação
- ISSUE -> Header

### Nilo e João:
- ISSUE -> RESP visualizar todos os eventos
- ISSUE -> RESP visualizar os detalhe de um evento
- ISSUE -> RESP visualizar a lista de todas as atividades
- ISSUE -> RESP visualizar os detalhes de uma atividade
- ISSUE -> RESP visualizar todos as anotações
- ISSUE -> RESP visualizar os detalhes de uma anotação

### PROXIMA SPRINT:
-   ISSUE -> RESP Home
-   ISSUE -> Listar turmas professor;
-   ISSUE -> Listar turmas admin;
-   ISSUE -> Sidebar
