### ISSUE TITLE
Pareamento Nilo - João | Sprint 8

### ISSUE THREAD

**Issue by NiloMendonca** [UnBArqDsw2021-1/2021.1_G6_Curumim_Front-end#9]
Issue direcionada para a implementação das seguintes funcionalidade:

- [x] Criação do perfil do Centro Educacional;
- [x] Criar tela de detalhes da Turma

**Comment by francisco1code** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Curumim-6107e813fcb8190017c01db0/issues/UnBArqDsw2021-1/2021.1_G6_Curumim_Front-end/9?planning-poker) with ZenHub @Bruno-Felix @DanielPortods @edsondearaujo @eliseukadesh67 @enzoggqs @gabrielbpn

**Comment by francisco1code** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Curumim-6107e813fcb8190017c01db0/issues/UnBArqDsw2021-1/2021.1_G6_Curumim_Front-end/9?planning-poker) with ZenHub @Joao-Pedro-Moura @NiloMendonca @omateusp
